# Local development: override git deps to use local checkouts.
[patch."https://github.com/shroudb/commons.git"]
shroudb-core = { path = "../commons/shroudb-core" }
shroudb-crypto = { path = "../commons/shroudb-crypto" }
shroudb-protocol-wire = { path = "../commons/shroudb-protocol-wire" }
shroudb-storage = { path = "../commons/shroudb-storage" }

[patch."https://github.com/shroudb/shroudb-transit.git"]
shroudb-transit-protocol = { path = "../shroudb-transit/shroudb-transit-protocol" }
shroudb-transit-core = { path = "../shroudb-transit/shroudb-transit-core" }
shroudb-transit-client = { path = "../shroudb-transit/shroudb-transit-client" }
